// List of words with Turkish and English meanings, and source information
const words = [
  {	id: "	1	",	french: "	blurry	",	turkish: "	 not clear	<br>	 bulanık	",	source: "	CELPIP-Word List	"},
{	id: "	2	",	french: "	cozy	",	turkish: "	 comfortable	<br>	 rahat, sıcak	",	source: "	CELPIP-Word List	"},
{	id: "	3	",	french: "	rigorous	",	turkish: "	 detailed or thorough	<br>	 titiz, sıkı	",	source: "	CELPIP-Word List	"},
{	id: "	4	",	french: "	rehearse	",	turkish: "	 practice	<br>	 prova yapmak	",	source: "	CELPIP-Word List	"},
{	id: "	5	",	french: "	allege	",	turkish: "	 blame	<br>	 iddia etmek	",	source: "	CELPIP-Word List	"},
{	id: "	6	",	french: "	convict	",	turkish: "	 criminal (noun) or criminally charging someone (verb)	<br>	 mahkûm etmek	",	source: "	CELPIP-Word List	"},
{	id: "	7	",	french: "	testify	",	turkish: "	 to bear witness	<br>	 tanıklık etmek	",	source: "	CELPIP-Word List	"},
{	id: "	8	",	french: "	verdict	",	turkish: "	 final decision	<br>	 karar	",	source: "	CELPIP-Word List	"},
{	id: "	9	",	french: "	adore	",	turkish: "	 appreciate	<br>	 çok sevmek	",	source: "	CELPIP-Word List	"},
{	id: "	10	",	french: "	envy	",	turkish: "	 be jealous of someone (verb)	<br>	 kıskanmak	",	source: "	CELPIP-Word List	"},
{	id: "	11	",	french: "	enthusiasm	",	turkish: "	 eagerness	<br>	 heves, coşku	",	source: "	CELPIP-Word List	"},
{	id: "	12	",	french: "	brag	",	turkish: "	 show off	<br>	 övünmek	",	source: "	CELPIP-Word List	"},
{	id: "	13	",	french: "	cautious	",	turkish: "	 careful	<br>	 tedbirli	",	source: "	CELPIP-Word List	"},
{	id: "	14	",	french: "	affection	",	turkish: "	 love or emotions	<br>	 sevgi, şefkat	",	source: "	CELPIP-Word List	"},
{	id: "	15	",	french: "	fond	",	turkish: "	 proud of	<br>	 düşkün	",	source: "	CELPIP-Word List	"},
{	id: "	16	",	french: "	poverty	",	turkish: "	 lack of money	<br>	 yoksulluk	",	source: "	CELPIP-Word List	"},
{	id: "	17	",	french: "	tenant/landlord	",	turkish: "	the one renting / the owner of the premises	<br>	 kiracı / ev sahibi	",	source: "	CELPIP-Word List	"},
{	id: "	18	",	french: "	slogan	",	turkish: "	 saying (mostly of companies)	<br>	 slogan	",	source: "	CELPIP-Word List	"},
{	id: "	19	",	french: "	valuable	",	turkish: "	 important	<br>	 değerli	",	source: "	CELPIP-Word List	"},
{	id: "	20	",	french: "	crew	",	turkish: "	 group	<br>	 ekip	",	source: "	CELPIP-Word List	"},
{	id: "	21	",	french: "	harvest	",	turkish: "	 to take out crops when they are fully grown	<br>	 hasat	",	source: "	CELPIP-Word List	"},
{	id: "	22	",	french: "	prosper	",	turkish: "	 to be successful	<br>	 zenginleşmek, başarılı olmak	",	source: "	CELPIP-Word List	"},
{	id: "	23	",	french: "	possess	",	turkish: "	 own something	<br>	 sahip olmak	",	source: "	CELPIP-Word List	"},
{	id: "	24	",	french: "	shallow	",	turkish: "	 not deep	<br>	 sığ	",	source: "	CELPIP-Word List	"},
{	id: "	25	",	french: "	fluid	",	turkish: "	 water like substance	<br>	 akışkan	",	source: "	CELPIP-Word List	"},
{	id: "	26	",	french: "	decay	",	turkish: "	 go bad	<br>	 çürüme	",	source: "	CELPIP-Word List	"},
{	id: "	27	",	french: "	batch	",	turkish: "	 group	<br>	 grup, parti	",	source: "	CELPIP-Word List	"},
{	id: "	28	",	french: "	aftermath	",	turkish: "	 after events	<br>	 sonuç, akıbet	",	source: "	CELPIP-Word List	"},
{	id: "	29	",	french: "	plethora	",	turkish: "	 a lot of	<br>	 aşırı bolluk	",	source: "	CELPIP-Word List	"},
{	id: "	30	",	french: "	temper	",	turkish: "	 mood	<br>	 öfke, ruh hali	",	source: "	CELPIP-Word List	"},
{	id: "	31	",	french: "	postpone	",	turkish: "	 delay	<br>	 ertelemek	",	source: "	CELPIP-Word List	"},
{	id: "	32	",	french: "	conceal	",	turkish: "	 hide	<br>	 gizlemek	",	source: "	CELPIP-Word List	"},
{	id: "	33	",	french: "	swap	",	turkish: "	 exchange	<br>	 takas yapmak	",	source: "	CELPIP-Word List	"},
{	id: "	34	",	french: "	exhaust	",	turkish: "	 use up	<br>	 tüketmek	",	source: "	CELPIP-Word List	"},
{	id: "	35	",	french: "	shrink	",	turkish: "	 become small	<br>	 küçülmek	",	source: "	CELPIP-Word List	"},
{	id: "	36	",	french: "	tremble	",	turkish: "	 shake	<br>	 titremek	",	source: "	CELPIP-Word List	"},
{	id: "	37	",	french: "	soak	",	turkish: "	 make wet in the water	<br>	 ıslatmak	",	source: "	CELPIP-Word List	"},
{	id: "	38	",	french: "	timid	",	turkish: "	 shy	<br>	 çekingen	",	source: "	CELPIP-Word List	"},
{	id: "	39	",	french: "	urge	",	turkish: "	 persuade	<br>	 dürtü	",	source: "	CELPIP-Word List	"},
{	id: "	40	",	french: "	agitate	",	turkish: "	 disturb	<br>	 kışkırtmak, heyecanlandırmak	",	source: "	CELPIP-Word List	"},
{	id: "	41	",	french: "	absolute	",	turkish: "	 the most or the greatest	<br>	 mutlak	",	source: "	CELPIP-Word List	"},
{	id: "	42	",	french: "	classify	",	turkish: "	 to attach a name to something	<br>	 sınıflandırmak	",	source: "	CELPIP-Word List	"},
{	id: "	43	",	french: "	scaffolding	",	turkish: "	 outer structure	<br>	 iskele	",	source: "	CELPIP-Word List	"},
{	id: "	44	",	french: "	supplant	",	turkish: "	 replace	<br>	 yerini almak	",	source: "	CELPIP-Word List	"},
{	id: "	45	",	french: "	aura	",	turkish: "	 vibes	<br>	 aura	",	source: "	CELPIP-Word List	"},
{	id: "	46	",	french: "	focal	",	turkish: "	 point of focus	<br>	 odak	",	source: "	CELPIP-Word List	"},
{	id: "	47	",	french: "	astray	",	turkish: "	 go away from the right path	<br>	 yoldan çıkmış	",	source: "	CELPIP-Word List	"},
{	id: "	48	",	french: "	pursue	",	turkish: "	 run after	<br>	 takip etmek	",	source: "	CELPIP-Word List	"},
{	id: "	49	",	french: "	aggregate	",	turkish: "	 total	<br>	 toplamak	",	source: "	CELPIP-Word List	"},
{	id: "	50	",	french: "	explicit	",	turkish: "	 to make clear	<br>	 açık, belirgin	",	source: "	CELPIP-Word List	"},
{	id: "	51	",	french: "	deviate	",	turkish: "	 move away from course	<br>	 sapmak	",	source: "	CELPIP-Word List	"},
{	id: "	52	",	french: "	arbitrary	",	turkish: "	 based on random judgement	<br>	 keyfi	",	source: "	CELPIP-Word List	"},
{	id: "	53	",	french: "	predominant	",	turkish: "	 powerful	<br>	 baskın	",	source: "	CELPIP-Word List	"},
{	id: "	54	",	french: "	indifferent	",	turkish: "	 not caring	<br>	 kayıtsız	",	source: "	CELPIP-Word List	"},
{	id: "	55	",	french: "	reinforce	",	turkish: "	 remind	<br>	 pekiştirmek	",	source: "	CELPIP-Word List	"},
{	id: "	56	",	french: "	considerable	",	turkish: "	 a lot	<br>	 önemli, hatırı sayılır	",	source: "	CELPIP-Word List	"},
{	id: "	57	",	french: "	constrain	",	turkish: "	 to limit someone	<br>	 kısıtlamak	",	source: "	CELPIP-Word List	"},
{	id: "	58	",	french: "	convene	",	turkish: "	 to come together	<br>	 toplamak	",	source: "	CELPIP-Word List	"},
{	id: "	59	",	french: "	correspond	",	turkish: "	 matches with	<br>	 karşılık gelmek, mektuplaşmak	",	source: "	CELPIP-Word List	"},
{	id: "	60	",	french: "	demonstrate	",	turkish: "	 show	<br>	 göstermek	",	source: "	CELPIP-Word List	"},
{	id: "	61	",	french: "	specify	",	turkish: "	 to give a title or assign a position	<br>	 belirtmek	",	source: "	CELPIP-Word List	"},
{	id: "	62	",	french: "	impose	",	turkish: "	 force	<br>	 dayatmak	",	source: "	CELPIP-Word List	"},
{	id: "	63	",	french: "	implicate	",	turkish: "	 to suggest something	<br>	 bulaştırmak, karıştırmak	",	source: "	CELPIP-Word List	"},
{	id: "	64	",	french: "	subsequent	",	turkish: "	 next	<br>	 sonraki	",	source: "	CELPIP-Word List	"},
{	id: "	65	",	french: "	despite	",	turkish: "	 instead	<br>	 rağmen	",	source: "	CELPIP-Word List	"},
{	id: "	66	",	french: "	hypothesis	",	turkish: "	 to assume after considering various options	<br>	 hipotez	",	source: "	CELPIP-Word List	"},
{	id: "	67	",	french: "	draft	",	turkish: "	 rough version	<br>	 taslak	",	source: "	CELPIP-Word List	"},
{	id: "	68	",	french: "	evolve	",	turkish: "	 to grow	<br>	 evrim geçirmek	",	source: "	CELPIP-Word List	"},
{	id: "	69	",	french: "	equivalent	",	turkish: "	 equal version	<br>	 eşdeğer	",	source: "	CELPIP-Word List	"},
{	id: "	70	",	french: "	adapting	",	turkish: "	 getting used to something	<br>	 uyum sağlamak	",	source: "	CELPIP-Word List	"},
{	id: "	71	",	french: "	advocate	",	turkish: "	 support	<br>	 savunmak, desteklemek	",	source: "	CELPIP-Word List	"},
{	id: "	72	",	french: "	equip	",	turkish: "	 to gift you with some tool	<br>	 donatmak	",	source: "	CELPIP-Word List	"},
{	id: "	73	",	french: "	empirical	",	turkish: "	 based on facts	<br>	 deneysel	",	source: "	CELPIP-Word List	"},
{	id: "	74	",	french: "	contrary	",	turkish: "	 opposite	<br>	 aksine	",	source: "	CELPIP-Word List	"},
{	id: "	75	",	french: "	ideology	",	turkish: "	 a set of beliefs	<br>	 ideoloji	",	source: "	CELPIP-Word List	"},
{	id: "	76	",	french: "	hierarchy	",	turkish: "	 a system of a management structure	<br>	 hiyerarşi	",	source: "	CELPIP-Word List	"},
{	id: "	77	",	french: "	intervene	",	turkish: "	 interrupt	<br>	 müdahale etmek	",	source: "	CELPIP-Word List	"},
{	id: "	78	",	french: "	successor	",	turkish: "	 one taking the office after you	<br>	 halef	",	source: "	CELPIP-Word List	"},
{	id: "	79	",	french: "	predecessor	",	turkish: "	 one taking the office before you	<br>	 selef	",	source: "	CELPIP-Word List	"},
{	id: "	80	",	french: "	undertake	",	turkish: "	 to take the responsibility of doing a task	<br>	 üstlenmek	",	source: "	CELPIP-Word List	"},
{	id: "	81	",	french: "	ignorant	",	turkish: "	 people who are not fully aware of situations with complete information	<br>	 cahil	",	source: "	CELPIP-Word List	"},
{	id: "	82	",	french: "	interval	",	turkish: "	 periods of time	<br>	 ara	",	source: "	CELPIP-Word List	"},
{	id: "	83	",	french: "	paradigm	",	turkish: "	 a way of thinking	<br>	 paradigma	",	source: "	CELPIP-Word List	"},
{	id: "	84	",	french: "	deviate	",	turkish: "	 move from the current course of action	<br>	 sapmak	",	source: "	CELPIP-Word List	"},
{	id: "	85	",	french: "	simulate	",	turkish: "	 copy	<br>	 simüle etmek	",	source: "	CELPIP-Word List	"},
{	id: "	86	",	french: "	distort	",	turkish: "	 to change the shape of something	<br>	 saptırmak	",	source: "	CELPIP-Word List	"},
{	id: "	87	",	french: "	sphere	",	turkish: "	 round object	<br>	 küre, alan	",	source: "	CELPIP-Word List	"},
{	id: "	88	",	french: "	restrain	",	turkish: "	 stop someone from doing something	<br>	 dizginlemek, kısıtlamak	",	source: "	CELPIP-Word List	"},
{	id: "	89	",	french: "	minimal	",	turkish: "	 very little	<br>	 minimum, asgari	",	source: "	CELPIP-Word List	"},
{	id: "	90	",	french: "	preliminary	",	turkish: "	 initial stages	<br>	 ön	",	source: "	CELPIP-Word List	"},
{	id: "	91	",	french: "	norm	",	turkish: "	 commonly accepted	<br>	 norm	",	source: "	CELPIP-Word List	"},
{	id: "	92	",	french: "	confine	",	turkish: "	 limit someone or something	<br>	 sınırlandırmak	",	source: "	CELPIP-Word List	"},
{	id: "	93	",	french: "	cease	",	turkish: "	 stop	<br>	 durdurmak	",	source: "	CELPIP-Word List	"},
{	id: "	94	",	french: "	coherent	",	turkish: "	 organized	<br>	 tutarlı	",	source: "	CELPIP-Word List	"},
{	id: "	95	",	french: "	coincide	",	turkish: "	 happen at the same time	<br>	 örtüşmek	",	source: "	CELPIP-Word List	"},
{	id: "	96	",	french: "	attain	",	turkish: "	 to get something tangible or intangible	<br>	 ulaşmak	",	source: "	CELPIP-Word List	"},
{	id: "	97	",	french: "	erode	",	turkish: "	 erase	<br>	 aşındırmak	",	source: "	CELPIP-Word List	"},
{	id: "	98	",	french: "	integral	",	turkish: "	 important	<br>	 ayrılmaz	",	source: "	CELPIP-Word List	"},
{	id: "	99	",	french: "	rigid	",	turkish: "	 difficult to change	<br>	 katı	",	source: "	CELPIP-Word List	"},
{	id: "	100	",	french: "	concurrent	",	turkish: "	 same as current	<br>	 eşzamanlı	",	source: "	CELPIP-Word List	"},
{	id: "	101	",	french: "	underlie	",	turkish: "	 to be the cause of something	<br>	 temelini oluşturmak	",	source: "	CELPIP-Word List	"},
{	id: "	102	",	french: "	initiate	",	turkish: "	 start	<br>	 başlatmak	",	source: "	CELPIP-Word List	"},
{	id: "	103	",	french: "	inhibit	",	turkish: "	 to prevent something from growing	<br>	 engellemek	",	source: "	CELPIP-Word List	"},
{	id: "	104	",	french: "	explicit	",	turkish: "	 detailed instructions (adjective)	<br>	 açık, belirgin	",	source: "	CELPIP-Word List	"},
{	id: "	105	",	french: "	cite	",	turkish: "	 to use something as a legitimate example	<br>	 alıntı yapmak	",	source: "	CELPIP-Word List	"},
{	id: "	106	",	french: "	clause	",	turkish: "	 a part of a legal agreement	<br>	 madde	",	source: "	CELPIP-Word List	"},
{	id: "	107	",	french: "	facilitate	",	turkish: "	 help someone achieve something	<br>	 kolaylaştırmak	",	source: "	CELPIP-Word List	"},
{	id: "	108	",	french: "	legit	",	turkish: "	 (informal) legal	<br>	 yasal	",	source: "	CELPIP-Word List	"},
{	id: "	109	",	french: "	discreet	",	turkish: "	 careful in one’s actions	<br>	 tedbirli, sağduyulu	",	source: "	CELPIP-Word List	"},
{	id: "	110	",	french: "	enabler	",	turkish: "	 someone who encourages someone else	<br>	 kolaylaştırıcı	",	source: "	CELPIP-Word List	"},
{	id: "	111	",	french: "	detractor	",	turkish: "	 opposite of enabler	<br>	 kötüleyen kişi	",	source: "	CELPIP-Word List	"},
{	id: "	112	",	french: "	disparage	",	turkish: "	 degrade	<br>	 küçümsemek	",	source: "	CELPIP-Word List	"},
{	id: "	113	",	french: "	dogma	",	turkish: "	 a set of firm believes	<br>	 dogma	",	source: "	CELPIP-Word List	"},
{	id: "	114	",	french: "	impulsive	",	turkish: "	 acting on impulse without thinking	<br>	 düşüncesizce hareket eden	",	source: "	CELPIP-Word List	"},
{	id: "	115	",	french: "	bash	",	turkish: "	 hurt someone physically or verbally	<br>	 şiddetle vurmak	",	source: "	CELPIP-Word List	"},
{	id: "	116	",	french: "	abstract	",	turkish: "	 existing in mind, not real	<br>	 soyut	",	source: "	CELPIP-Word List	"},
{	id: "	117	",	french: "	abysmal	",	turkish: "	 terrible	<br>	 berbat	",	source: "	CELPIP-Word List	"},
{	id: "	118	",	french: "	clinical	",	turkish: "	 not emotionally involved	<br>	 klinik	",	source: "	CELPIP-Word List	"},
{	id: "	119	",	french: "	conceive	",	turkish: "	 come up with an idea	<br>	 tasarlamak	",	source: "	CELPIP-Word List	"},
{	id: "	120	",	french: "	conducive	",	turkish: "	 suited to	<br>	 elverişli	",	source: "	CELPIP-Word List	"},
{	id: "	121	",	french: "	confide	",	turkish: "	 express real feelings	<br>	 sır vermek	",	source: "	CELPIP-Word List	"},
{	id: "	122	",	french: "	dubious	",	turkish: "	 doubtful	<br>	 şüpheli	",	source: "	CELPIP-Word List	"},
{	id: "	123	",	french: "	eloquent	",	turkish: "	 very expressive	<br>	 güzel konuşan	",	source: "	CELPIP-Word List	"},
{	id: "	124	",	french: "	envy	",	turkish: "	 to be jealous	<br>	 kıskanmak	",	source: "	CELPIP-Word List	"},
{	id: "	125	",	french: "	imprudent	",	turkish: "	 rude	<br>	 düşüncesiz	",	source: "	CELPIP-Word List	"},
{	id: "	126	",	french: "	scandalous	",	turkish: "	 morally offensive	<br>	 skandal niteliğinde	",	source: "	CELPIP-Word List	"},
{	id: "	127	",	french: "	surmount	",	turkish: "	 to overcome	<br>	 üstesinden gelmek	",	source: "	CELPIP-Word List	"},
{	id: "	128	",	french: "	validate	",	turkish: "	 to prove	<br>	 doğrulamak	",	source: "	CELPIP-Word List	"},
{	id: "	129	",	french: "	unveil	",	turkish: "	 make something possible	<br>	 ortaya çıkarmak	",	source: "	CELPIP-Word List	"},
{	id: "	130	",	french: "	vital	",	turkish: "	 necessary	<br>	 hayati	",	source: "	CELPIP-Word List	"},
{	id: "	131	",	french: "	exceptional	",	turkish: "	good	<br>	 istisnai	",	source: "	CELPIP-Word List	"},
{	id: "	132	",	french: "	recent	",	turkish: "	new	<br>	 son zamanlardaki	",	source: "	CELPIP-Word List	"},
{	id: "	133	",	french: "	lingering	",	turkish: "	long	<br>	 uzun süren	",	source: "	CELPIP-Word List	"},
{	id: "	134	",	french: "	decaying	",	turkish: "	old	<br>	 çürüyen	",	source: "	CELPIP-Word List	"},
{	id: "	135	",	french: "	precise	",	turkish: "	right	<br>	 kesin	",	source: "	CELPIP-Word List	"},
{	id: "	136	",	french: "	oddorexotic	",	turkish: "	different	<br>	 tuhaf veya egzotik	",	source: "	CELPIP-Word List	"},
{	id: "	137	",	french: "	immenseormassive	",	turkish: "	large	<br>	 çok büyük	",	source: "	CELPIP-Word List	"},
{	id: "	138	",	french: "	youthful	",	turkish: "	young	<br>	 genç	",	source: "	CELPIP-Word List	"},
{	id: "	139	",	french: "	sparsely	",	turkish: "	never	<br>	 seyrek	",	source: "	CELPIP-Word List	"},
{	id: "	140	",	french: "	belongings	",	turkish: "	things	<br>	 eşyalar	",	source: "	CELPIP-Word List	"},
{	id: "	141	",	french: "	discern	",	turkish: "	feel	<br>	 fark etmek	",	source: "	CELPIP-Word List	"},
{	id: "	142	",	french: "	comeacrossas	",	turkish: "	seem	<br>	 gibi görünmek	",	source: "	CELPIP-Word List	"},
{	id: "	143	",	french: "	hardly	",	turkish: "	just	<br>	 neredeyse hiç	",	source: "	CELPIP-Word List	"},
{	id: "	144	",	french: "	upcoming	",	turkish: "	next	<br>	 yakında olacak	",	source: "	CELPIP-Word List	"},
{	id: "	145	",	french: "	plausible	",	turkish: "	possible	<br>	 makul	",	source: "	CELPIP-Word List	"},
{	id: "	146	",	french: "	ambiguous	",	turkish: "	 not clear	<br>	 belirsiz	",	source: "	CELPIP-Word List	"},
{	id: "	147	",	french: "	conform	",	turkish: "	 to agree with the norm	<br>	 uymak	",	source: "	CELPIP-Word List	"},
{	id: "	148	",	french: "	evident	",	turkish: "	 clear	<br>	 belirgin	",	source: "	CELPIP-Word List	"},
{	id: "	149	",	french: "	implicate	",	turkish: "	 to accuse someone of being involved in a crime or something negative	<br>	 bulaştırmak, karıştırmak	",	source: "	CELPIP-Word List	"},
{	id: "	150	",	french: "	append	",	turkish: "	 fix or attach	<br>	 eklemek	",	source: "	CELPIP-Word List	"},
{	id: "	151	",	french: "	partisan	",	turkish: "	 biased	<br>	 taraflı	",	source: "	CELPIP-Word List	"},
{	id: "	152	",	french: "	discrete	",	turkish: "	 separate	<br>	 ayrı	",	source: "	CELPIP-Word List	"},
{	id: "	153	",	french: "	infer	",	turkish: "	 conclude	<br>	 çıkarım yapmak	",	source: "	CELPIP-Word List	"},
{	id: "	154	",	french: "	inherent	",	turkish: "	 something existing as a characteristic	<br>	 doğuştan gelen	",	source: "	CELPIP-Word List	"},
{	id: "	155	",	french: "	reluctance	",	turkish: "	 unwillingness	<br>	 isteksizlik	",	source: "	CELPIP-Word List	"},
{	id: "	156	",	french: "	precede	",	turkish: "	 come earlier in sequence	<br>	 önce gelmek	",	source: "	CELPIP-Word List	"},
{	id: "	157	",	french: "	offset	",	turkish: "	 use something as compensation	<br>	 dengelemek	",	source: "	CELPIP-Word List	"},
{	id: "	158	",	french: "	prognosticate	",	turkish: "	 predict (something serious)	<br>	 tahmin etmek	",	source: "	CELPIP-Word List	"},
{	id: "	159	",	french: "	mediate	",	turkish: "	 reconcile differences between two parties	<br>	 arabuluculuk yapmak	",	source: "	CELPIP-Word List	"},
{	id: "	160	",	french: "	rigid	",	turkish: "	 stubborn, not moving	<br>	 katı	",	source: "	CELPIP-Word List	"},
{	id: "	161	",	french: "	abate	",	turkish: "	 to lessen	<br>	 hafifletmek	",	source: "	CELPIP-Word List	"},
{	id: "	162	",	french: "	adversity	",	turkish: "	 problematic situations	<br>	 sıkıntı, zorluk	",	source: "	CELPIP-Word List	"},
{	id: "	163	",	french: "	brazen	",	turkish: "	 bold	<br>	 utanmaz	",	source: "	CELPIP-Word List	"},
{	id: "	164	",	french: "	condescending	",	turkish: "	 looking down on someone	<br>	 küçümseyen	",	source: "	CELPIP-Word List	"},
{	id: "	165	",	french: "	mundane	",	turkish: "	 boring	<br>	 sıradan	",	source: "	CELPIP-Word List	"},
{	id: "	166	",	french: "	reverence	",	turkish: "	 deep respect	<br>	 saygı	",	source: "	CELPIP-Word List	"},
{	id: "	167	",	french: "	prosperity	",	turkish: "	 wealth	<br>	 refah	",	source: "	CELPIP-Word List	"},
{	id: "	168	",	french: "	canny	",	turkish: "	 careful	<br>	 kurnaz	",	source: "	CELPIP-Word List	"},
{	id: "	169	",	french: "	disdain	",	turkish: "	 to show hate	<br>	 küçümseme	",	source: "	CELPIP-Word List	"},
{	id: "	170	",	french: "	intuitive	",	turkish: "	 knowing something with intuition	<br>	 sezgisel	",	source: "	CELPIP-Word List	"},
{	id: "	171	",	french: "	spontaneous	",	turkish: "	 do something without thinking/abruptly	<br>	 spontane	",	source: "	CELPIP-Word List	"},
{	id: "	172	",	french: "	superfluous	",	turkish: "	 unnecessary	<br>	 gereksiz	",	source: "	CELPIP-Word List	"},
{	id: "	173	",	french: "	null	",	turkish: "	 void	<br>	 geçersiz	",	source: "	CELPIP-Word List	"},
{	id: "	174	",	french: "	vindicate	",	turkish: "	 to free from blame	<br>	 aklamak	",	source: "	CELPIP-Word List	"},
{	id: "	175	",	french: "	entail	",	turkish: "	 involve	<br>	 gerektirmek	",	source: "	CELPIP-Word List	"},
{	id: "	176	",	french: "	arid	",	turkish: "	 very dry	<br>	 kuru	",	source: "	CELPIP-Word List	"},
{	id: "	177	",	french: "	frugal	",	turkish: "	 stingy	<br>	 tutumlu	",	source: "	CELPIP-Word List	"},
{	id: "	178	",	french: "	convergence	",	turkish: "	 coming together	<br>	 yakınsama	",	source: "	CELPIP-Word List	"},
{	id: "	179	",	french: "	diligent	",	turkish: "	 hardworking	<br>	 çalışkan	",	source: "	CELPIP-Word List	"},
{	id: "	180	",	french: "	intrepid	",	turkish: "	 fearless	<br>	 cesur	",	source: "	CELPIP-Word List	"},
{	id: "	181	",	french: "	orator	",	turkish: "	 speaker	<br>	 hatip	",	source: "	CELPIP-Word List	"},
{	id: "	182	",	french: "	parched	",	turkish: "	 when something is dried up	<br>	 susuz kalmış	",	source: "	CELPIP-Word List	"},
{	id: "	183	",	french: "	reclusive	",	turkish: "	 avoiding other people	<br>	 inzivaya çekilmiş	",	source: "	CELPIP-Word List	"},
{	id: "	184	",	french: "	reconciliation	",	turkish: "	 bringing people together	<br>	 uzlaşma	",	source: "	CELPIP-Word List	"},
{	id: "	185	",	french: "	haughty	",	turkish: "	 being arrogant	<br>	 kibirli	",	source: "	CELPIP-Word List	"},
{	id: "	186	",	french: "	aberration	",	turkish: "	 something unusual	<br>	 sapma	",	source: "	CELPIP-Word List	"},
{	id: "	187	",	french: "	jubilation	",	turkish: "	 extreme happiness	<br>	 sevinç	",	source: "	CELPIP-Word List	"},
{	id: "	188	",	french: "	apex	",	turkish: "	 top or high point	<br>	 zirve	",	source: "	CELPIP-Word List	"},
{	id: "	189	",	french: "	capacious	",	turkish: "	 having a lot of space	<br>	 geniş	",	source: "	CELPIP-Word List	"},
{	id: "	190	",	french: "	delirious	",	turkish: "	 not being in a normal state of mind	<br>	 sayıklayan	",	source: "	CELPIP-Word List	"},
{	id: "	191	",	french: "	kindle	",	turkish: "	 start a fire	<br>	 ateş yakmak	",	source: "	CELPIP-Word List	"},
{	id: "	192	",	french: "	noxious	",	turkish: "	 lethal	<br>	 zararlı	",	source: "	CELPIP-Word List	"},
{	id: "	193	",	french: "	hangar	",	turkish: "	 storage area for a plane	<br>	 hangar	",	source: "	CELPIP-Word List	"},
{	id: "	194	",	french: "	cower	",	turkish: "	 move as in you are in fear	<br>	 sinmek	",	source: "	CELPIP-Word List	"},
{	id: "	195	",	french: "	tangible	",	turkish: "	 can be touched	<br>	 somut	",	source: "	CELPIP-Word List	"},
{	id: "	196	",	french: "	credible	",	turkish: "	 believable	<br>	 güvenilir	",	source: "	CELPIP-Word List	"},
{	id: "	197	",	french: "	tardy	",	turkish: "	 sluggish	<br>	 geç	",	source: "	CELPIP-Word List	"},
{	id: "	198	",	french: "	blatant	",	turkish: "	 obvious	<br>	 bariz	",	source: "	CELPIP-Word List	"},
{	id: "	199	",	french: "	hasten	",	turkish: "	 make something faster	<br>	 hızlandırmak	",	source: "	CELPIP-Word List	"},
{	id: "	200	",	french: "	abstain	",	turkish: "	 avoid something	<br>	 kaçınmak	",	source: "	CELPIP-Word List	"},
{	id: "	201	",	french: "	repudiate	",	turkish: "	 nullify something	<br>	 reddetmek	",	source: "	CELPIP-Word List	"},
{	id: "	202	",	french: "	cringe	",	turkish: "	 become uncomfortable	<br>	 çekinmek	",	source: "	CELPIP-Word List	"},
{	id: "	203	",	french: "	tenacious	",	turkish: "	 aggressive or stubborn	<br>	 azimli	",	source: "	CELPIP-Word List	"},
{	id: "	204	",	french: "	cryptic	",	turkish: "	 puzzling	<br>	 gizemli	",	source: "	CELPIP-Word List	"},
{	id: "	205	",	french: "	lampoon	",	turkish: "	 ridiculous	<br>	 taşlamak	",	source: "	CELPIP-Word List	"},
{	id: "	206	",	french: "	admonish	",	turkish: "	 scold	<br>	 uyarmak	",	source: "	CELPIP-Word List	"},
{	id: "	207	",	french: "	alias	",	turkish: "	 temporary name	<br>	 takma ad	",	source: "	CELPIP-Word List	"},
{	id: "	208	",	french: "	assiduous	",	turkish: "	 similar to hardworking	<br>	 gayretli	",	source: "	CELPIP-Word List	"},
{	id: "	209	",	french: "	circumvent	",	turkish: "	 surround the enemy to make them give up	<br>	 atlatmak	",	source: "	CELPIP-Word List	"},
{	id: "	210	",	french: "	cognizant	",	turkish: "	 knowledgeable or aware about something	<br>	 farkında	",	source: "	CELPIP-Word List	"},
{	id: "	211	",	french: "	debacle	",	turkish: "	 complete disaster	<br>	 bozgun	",	source: "	CELPIP-Word List	"},
{	id: "	212	",	french: "	debunk	",	turkish: "	 clarify a mystery	<br>	 çürütmek	",	source: "	CELPIP-Word List	"},
{	id: "	213	",	french: "	eclectic	",	turkish: "	 a dynamic range of something	<br>	 seçmeci	",	source: "	CELPIP-Word List	"},
{	id: "	214	",	french: "	emulate	",	turkish: "	 to copy someone as a role model	<br>	 taklit etmek	",	source: "	CELPIP-Word List	"},
{	id: "	215	",	french: "	hapless	",	turkish: "	 something that fails and deserves pit	<br>	 talihsiz	",	source: "	CELPIP-Word List	"},
{	id: "	216	",	french: "	incontrovertible	",	turkish: "	 something that cannot be denied	<br>	 tartışılmaz	",	source: "	CELPIP-Word List	"},
{	id: "	217	",	french: "	negligent	",	turkish: "	 someone not paying attention to their duties	<br>	 ihmalkâr	",	source: "	CELPIP-Word List	"},
{	id: "	218	",	french: "	insidious	",	turkish: "	 something hidden and harmful	<br>	 sinsi	",	source: "	CELPIP-Word List	"},
{	id: "	219	",	french: "	laconic	",	turkish: "	 to the point	<br>	 kısa ve öz	",	source: "	CELPIP-Word List	"},
{	id: "	220	",	french: "	maverick	",	turkish: "	 someone who shows independence	<br>	 başına buyruk	",	source: "	CELPIP-Word List	"},
{	id: "	221	",	french: "	amorphous	",	turkish: "	 no shape	<br>	 biçimsiz	",	source: "	CELPIP-Word List	"},
{	id: "	222	",	french: "	candor	",	turkish: "	 being straightforward	<br>	 samimiyet	",	source: "	CELPIP-Word List	"},
{	id: "	223	",	french: "	capitulate	",	turkish: "	 surrender	<br>	 teslim olmak	",	source: "	CELPIP-Word List	"},
{	id: "	224	",	french: "	conduit	",	turkish: "	 a passage	<br>	 boru hattı	",	source: "	CELPIP-Word List	"},
{	id: "	225	",	french: "	disrepute	",	turkish: "	 bringing low respect	<br>	 itibarsızlık	",	source: "	CELPIP-Word List	"},
{	id: "	226	",	french: "	duplicity	",	turkish: "	 the act of being fake	<br>	 ikiyüzlülük	",	source: "	CELPIP-Word List	"},
{	id: "	227	",	french: "	fallacious	",	turkish: "	 based on the wrong reasoning	<br>	 yanıltıcı	",	source: "	CELPIP-Word List	"},
{	id: "	228	",	french: "	linchpin	",	turkish: "	 a central authority	<br>	 kilit nokta	",	source: "	CELPIP-Word List	"},
{	id: "	229	",	french: "	ostensible	",	turkish: "	 looks that appear as something but are actually deceiving	<br>	 görünürdeki	",	source: "	CELPIP-Word List	"},
{	id: "	230	",	french: "	proclivity	",	turkish: "	 the intention or inclination to do something	<br>	 eğilim	",	source: "	CELPIP-Word List	"},
{	id: "	231	",	french: "	ramble	",	turkish: "	 to go off saying things continuously which are not relevant	<br>	 boş konuşmak	",	source: "	CELPIP-Word List	"},
{	id: "	232	",	french: "	vilify	",	turkish: "	 make someone the bad guy	<br>	 kötülemek	",	source: "	CELPIP-Word List	"},
{	id: "	233	",	french: "	languish	",	turkish: "	 lose beauty or charm	<br>	 güçsüzleşmek	",	source: "	CELPIP-Word List	"},
{	id: "	234	",	french: "	pariah	",	turkish: "	 a social outcast	<br>	 dışlanmış	",	source: "	CELPIP-Word List	"},
{	id: "	235	",	french: "	maxim	",	turkish: "	 short statement backed by facts	<br>	 özdeyiş	",	source: "	CELPIP-Word List	"},
{	id: "	236	",	french: "	aggrandize	",	turkish: "	 to enhance power	<br>	 büyütmek	",	source: "	CELPIP-Word List	"},
{	id: "	237	",	french: "	beguile	",	turkish: "	 to influence in a deceptive way	<br>	 kandırmak	",	source: "	CELPIP-Word List	"},
{	id: "	238	",	french: "	archetypal	",	turkish: "	 typical	<br>	 arketipsel	",	source: "	CELPIP-Word List	"},
{	id: "	239	",	french: "	callous	",	turkish: "	 disregard for others	<br>	 duyarsız	",	source: "	CELPIP-Word List	"},
{	id: "	240	",	french: "	cognizant	",	turkish: "	 being aware of something	<br>	 farkında	",	source: "	CELPIP-Word List	"},
{	id: "	241	",	french: "	construe	",	turkish: "	 the way something is interpreted	<br>	 yorumlamak	",	source: "	CELPIP-Word List	"},
{	id: "	242	",	french: "	disparate	",	turkish: "	 completely different	<br>	 farklı	",	source: "	CELPIP-Word List	"},
{	id: "	243	",	french: "	denigrate	",	turkish: "	 criticize harshly	<br>	 karalamak	",	source: "	CELPIP-Word List	"},
{	id: "	244	",	french: "	idiosyncratic	",	turkish: "	 something unique about someone	<br>	 kendine özgü	",	source: "	CELPIP-Word List	"},
{	id: "	245	",	french: "	inveterate	",	turkish: "	 habitual	<br>	 kökleşmiş	",	source: "	CELPIP-Word List	"},
{	id: "	246	",	french: "	multifarious	",	turkish: "	 diverse	<br>	 çeşitli	",	source: "	CELPIP-Word List	"},
{	id: "	247	",	french: "	largesse	",	turkish: "	 generosity	<br>	 cömertlik	",	source: "	CELPIP-Word List	"},
{	id: "	248	",	french: "	obdurate	",	turkish: "	 stubborn	<br>	 inatçı	",	source: "	CELPIP-Word List	"},
{	id: "	249	",	french: "	promulgate	",	turkish: "	 to spread or broadcast	<br>	 yaymak	",	source: "	CELPIP-Word List	"},
{	id: "	250	",	french: "	phlegmatic	",	turkish: "	 showing no emotion	<br>	 soğukkanlı	",	source: "	CELPIP-Word List	"},
{	id: "	251	",	french: "	accord	",	turkish: "	 something consistent with the other or in agreement	<br>	 uzlaşma	",	source: "	CELPIP-Word List	"},
{	id: "	252	",	french: "	astounding	",	turkish: "	 amazing	<br>	 şaşırtıcı	",	source: "	CELPIP-Word List	"},
{	id: "	253	",	french: "	armored	",	turkish: "	 fully sealed or protected	<br>	 zırhlı	",	source: "	CELPIP-Word List	"},
{	id: "	254	",	french: "	divest	",	turkish: "	 to deprive someone something	<br>	 elden çıkarmak	",	source: "	CELPIP-Word List	"},
{	id: "	255	",	french: "	debrief	",	turkish: "	 to question someone	<br>	 brifing vermek	",	source: "	CELPIP-Word List	"},
{	id: "	256	",	french: "	docile	",	turkish: "	 obedient	<br>	 uysal	",	source: "	CELPIP-Word List	"},
{	id: "	257	",	french: "	fluster	",	turkish: "	 to confuse someone	<br>	 telaşlandırmak	",	source: "	CELPIP-Word List	"},
{	id: "	258	",	french: "	fetter	",	turkish: "	 to bound or restrain someone	<br>	 zincirlemek	",	source: "	CELPIP-Word List	"},
{	id: "	259	",	french: "	fuse	",	turkish: "	 to mix or blend together	<br>	 kaynaştırmak	",	source: "	CELPIP-Word List	"},
{	id: "	260	",	french: "	rudimentary	",	turkish: "	 basic	<br>	 temel	",	source: "	CELPIP-Word List	"},
{	id: "	261	",	french: "	tempest	",	turkish: "	 violent or windy storm	<br>	 fırtına	",	source: "	CELPIP-Word List	"},
{	id: "	262	",	french: "	taint	",	turkish: "	 to make something worse or ugly	<br>	 lekelemek	",	source: "	CELPIP-Word List	"},
{	id: "	263	",	french: "	tactless	",	turkish: "	 not showing sensitivity or care	<br>	 patavatsız	",	source: "	CELPIP-Word List	"},
{	id: "	264	",	french: "	adroit	",	turkish: "	 full of talent	<br>	 becerikli	",	source: "	CELPIP-Word List	"},
{	id: "	265	",	french: "	peptalk	",	turkish: "	 encouraging words	<br>	 gaz verme konuşması	",	source: "	CELPIP-Word List	"},
{	id: "	266	",	french: "	proclaim	",	turkish: "	 declare something of importance	<br>	 ilan etmek	",	source: "	CELPIP-Word List	"},
{	id: "	267	",	french: "	lethargic	",	turkish: "	 lazy	<br>	 uyuşuk	",	source: "	CELPIP-Word List	"},
{	id: "	268	",	french: "	considerable	",	turkish: "	 great	<br>	 önemli	",	source: "	CELPIP-Word List	"},
{	id: "	269	",	french: "	downright	",	turkish: "	 complete or total	<br>	 düpedüz	",	source: "	CELPIP-Word List	"},
{	id: "	270	",	french: "	explicit	",	turkish: "	 clear or detailed	<br>	 açık	",	source: "	CELPIP-Word List	"},
{	id: "	271	",	french: "	forthright	",	turkish: "	 straightforward and honest	<br>	 açık sözlü	",	source: "	CELPIP-Word List	"},
{	id: "	272	",	french: "	full-blown	",	turkish: "	 massive	<br>	 tam gelişmiş	",	source: "	CELPIP-Word List	"},
{	id: "	273	",	french: "	constrain	",	turkish: "	 compel someone	<br>	 kısıtlamak	",	source: "	CELPIP-Word List	"},
{	id: "	274	",	french: "	vehement	",	turkish: "	 showing strong passion	<br>	 şiddetli	",	source: "	CELPIP-Word List	"},
{	id: "	275	",	french: "	dawdle	",	turkish: "	 to waste time	<br>	 oyalanmak	",	source: "	CELPIP-Word List	"},
{	id: "	276	",	french: "	retardment	",	turkish: "	 the delay in processing something	<br>	 yavaşlama	",	source: "	CELPIP-Word List	"},
{	id: "	277	",	french: "	showstopper	",	turkish: "	 something that deserves applause	<br>	 dikkat çeken şey	",	source: "	CELPIP-Word List	"},
{	id: "	278	",	french: "	cessation	",	turkish: "	 stopping something	<br>	 durma	",	source: "	CELPIP-Word List	"},
{	id: "	279	",	french: "	expedition	",	turkish: "	 a quest to discover something	<br>	 sefer	",	source: "	CELPIP-Word List	"},
{	id: "	280	",	french: "	hustle	",	turkish: "	 to get something by forceful action	<br>	 itiş kakış	",	source: "	CELPIP-Word List	"},
{	id: "	281	",	french: "	engrossed	",	turkish: "	 completely occupied in some activity	<br>	 dalmış	",	source: "	CELPIP-Word List	"},
{	id: "	282	",	french: "	astute	",	turkish: "	 very smart or sharp	<br>	 zeki	",	source: "	CELPIP-Word List	"},
{	id: "	283	",	french: "	visceral	",	turkish: "	 something inside your body OR a deep feeling	<br>	 içgüdüsel	",	source: "	CELPIP-Word List	"},
{	id: "	284	",	french: "	lateral	",	turkish: "	 at or toward or the side. It points to something	<br>	 yanal	",	source: "	CELPIP-Word List	"},
{	id: "	285	",	french: "	presumptuous	",	turkish: "	 someone who does not know what is appropriate in certain situations	<br>	 küstah	",	source: "	CELPIP-Word List	"},
{	id: "	286	",	french: "	oversight(noun)	",	turkish: "	 missing something while making analysis	<br>	 gözetim, denetim	",	source: "	CELPIP-Word List	"},
{	id: "	287	",	french: "	pretentious	",	turkish: "	 faking something or showing off	<br>	 gösterişli	",	source: "	CELPIP-Word List	"},
{	id: "	288	",	french: "	win-win	",	turkish: "	 when both sides win	<br>	 kazan-kazan	",	source: "	CELPIP-Word List	"},
{	id: "	289	",	french: "	pushtheenvelope	",	turkish: "	 push the limits of something	<br>	 sınırları zorlamak	",	source: "	CELPIP-Word List	"},
{	id: "	290	",	french: "	bendingbackwards	",	turkish: "	 to try something really difficult	<br>	 geri bükülme	",	source: "	CELPIP-Word List	"},
{	id: "	291	",	french: "	rustic	",	turkish: "	 plain and very simple	<br>	 kırsal	",	source: "	CELPIP-Word List	"},
{	id: "	292	",	french: "	proactive	",	turkish: "	 responding to situations with your feelings or attitude rather than reacting to them	<br>	 proaktif	",	source: "	CELPIP-Word List	"},
{	id: "	293	",	french: "	reimagine	",	turkish: "	 think of something again	<br>	 yeniden hayal etmek	",	source: "	CELPIP-Word List	"},
{	id: "	294	",	french: "	higherorderthinking	",	turkish: "	 thinking beyond simple memorization	<br>	 üst düzey düşünme	",	source: "	CELPIP-Word List	"},
{	id: "	295	",	french: "	ballpark	",	turkish: "	 rough estimate	<br>	 tahmini	",	source: "	CELPIP-Word List	"},
{	id: "	296	",	french: "	corecompetency	",	turkish: "	 your advantage that distinguishes you from others	<br>	 temel yetkinlik	",	source: "	CELPIP-Word List	"},
{	id: "	297	",	french: "	entitlement	",	turkish: "	 your privilege to have something	<br>	 hak	",	source: "	CELPIP-Word List	"},
{	id: "	298	",	french: "	holistic	",	turkish: "	 the complete thing	<br>	 bütünsel	",	source: "	CELPIP-Word List	"},
{	id: "	299	",	french: "	toil	",	turkish: "	 hard work (noun) OR to do hard work (verb)	<br>	 didinmek	",	source: "	CELPIP-Word List	"},
{	id: "	300	",	french: "	pester	",	turkish: "	 to annoy someone	<br>	 rahatsız etmek	",	source: "	CELPIP-Word List	"},
{	id: "	301	",	french: "	porringer	",	turkish: "	 a small bowl	<br>	 kase	",	source: "	CELPIP-Word List	"},
{	id: "	302	",	french: "	backhaul	",	turkish: "	 return trip of a vehicle	<br>	 taşıma işlemi	",	source: "	CELPIP-Word List	"},
{	id: "	303	",	french: "	gaslight	",	turkish: "	 to manipulate someone	<br>	 psikolojik baskı yapmak	",	source: "	CELPIP-Word List	"},
{	id: "	304	",	french: "	awfulize	",	turkish: "	 to make something sound awful	<br>	 kötüleştirmek	",	source: "	CELPIP-Word List	"},
{	id: "	305	",	french: "	hench	",	turkish: "	 a muscular, strong person	<br>	 kaslı	",	source: "	CELPIP-Word List	"},
{	id: "	306	",	french: "	microtarget	",	turkish: "	 to target a person or people based on all data available about them	<br>	 mikro hedefleme	",	source: "	CELPIP-Word List	"},
{	id: "	307	",	french: "	patientzero	",	turkish: "	 the first patient identified of a certain disease	<br>	 ilk hasta	",	source: "	CELPIP-Word List	"},
{	id: "	308	",	french: "	sadfishing	",	turkish: "	 using social media to exaggerate one’s pain in order to gain sympathy	<br>	 üzülme rolü yapma	",	source: "	CELPIP-Word List	"},
{	id: "	309	",	french: "	amplify	",	turkish: "	 make something bigger	<br>	 yükseltmek	",	source: "	CELPIP-Word List	"},
{	id: "	310	",	french: "	unfathom	",	turkish: "	 starting to comprehend something	<br>	 anlaşılmaz	",	source: "	CELPIP-Word List	"},
{	id: "	311	",	french: "	dread	",	turkish: "	 feeling of fear	<br>	 korku	",	source: "	CELPIP-Word List	"},
{	id: "	312	",	french: "	anxiety	",	turkish: "	 nervousness or feeling alarmed	<br>	 kaygı	",	source: "	CELPIP-Word List	"},
{	id: "	313	",	french: "	grief	",	turkish: "	 feeling of sorrow	<br>	 keder	",	source: "	CELPIP-Word List	"},
{	id: "	314	",	french: "	bland	",	turkish: "	 tasteless	<br>	 tatsız	",	source: "	CELPIP-Word List	"},
{	id: "	315	",	french: "	ache	",	turkish: "	 pain	<br>	 ağrı	",	source: "	CELPIP-Word List	"},
{	id: "	316	",	french: "	fatigue	",	turkish: "	 tiredness	<br>	 yorgunluk	",	source: "	CELPIP-Word List	"},
{	id: "	317	",	french: "	sanitary	",	turkish: "	 related to health	<br>	 hijyenik	",	source: "	CELPIP-Word List	"},
{	id: "	318	",	french: "	sore	",	turkish: "	 part of your body under pain	<br>	 ağrılı	",	source: "	CELPIP-Word List	"},
{	id: "	319	",	french: "	trauma	",	turkish: "	 physical or mental pain	<br>	 travma	",	source: "	CELPIP-Word List	"},
{	id: "	320	",	french: "	slender	",	turkish: "	thin	<br>	 ince	",	source: "	CELPIP-Word List	"},
{	id: "	321	",	french: "	bruise	",	turkish: "	 injury	<br>	 çürük	",	source: "	CELPIP-Word List	"},
{	id: "	322	",	french: "	bargain	",	turkish: "	 to argue	<br>	 pazarlık	",	source: "	CELPIP-Word List	"},
{	id: "	323	",	french: "	affiliate	",	turkish: "	 to link	<br>	 bağlı kuruluş	",	source: "	CELPIP-Word List	"},
{	id: "	324	",	french: "	surplus	",	turkish: "	 excess of something	<br>	 fazlalık	",	source: "	CELPIP-Word List	"},
{	id: "	325	",	french: "	venture	",	turkish: "	 business activity involving risks	<br>	 girişim	",	source: "	CELPIP-Word List	"},
{	id: "	326	",	french: "	How do I make it FEASIBLE?	",	turkish: "	It’s hard for me to do	<br>	 Bunu yapmak benim için zor	",	source: "	CELPIP-Word List	"},
{	id: "	327	",	french: "	How can I be PERSISTENT?	",	turkish: "	I want to quit	<br>	 Bırakmak istiyorum	",	source: "	CELPIP-Word List	"},
{	id: "	328	",	french: "	I have CONVICTION that I can earn $50,000/yr	",	turkish: "	I can earn $50,000/yr	<br>	 Yılda 50,000$ kazanabilirim	",	source: "	CELPIP-Word List	"},
{	id: "	329	",	french: "	I feel MY FATE is to win this competition	",	turkish: "	I feel positive that I can win this competition	<br>	 Bu yarışmayı kazanabileceğim konusunda olumlu hissediyorum	",	source: "	CELPIP-Word List	"},
{	id: "	330	",	french: "	I have FAITH that I can do it	",	turkish: "	I believe that I can do it	<br>	 Bunu yapabileceğime inanıyorum	",	source: "	CELPIP-Word List	"},
{	id: "	331	",	french: "	I am OPTIMISTIC	",	turkish: "	I feel bad	<br>	 Kendimi kötü hissediyorum	",	source: "	CELPIP-Word List	"},
{	id: "	332	",	french: "	I have AMPLE luxuries	",	turkish: "	I have less luxuries	<br>	 Daha az lüksüm var	",	source: "	CELPIP-Word List	"},
{	id: "	333	",	french: "	I am CONTENDED with life	",	turkish: "	I am okay with things	<br>	 Durumdan memnunum	",	source: "	CELPIP-Word List	"},
{	id: "	334	",	french: "	I am PASSIONATE for money	",	turkish: "	I am hungry for money	<br>	 Paraya açım	",	source: "	CELPIP-Word List	"},
{	id: "	335	",	french: "	I like to FLOURISH	",	turkish: "	I like to grow	<br>	 Büyümeyi severim	",	source: "	CELPIP-Word List	"},
{	id: "	336	",	french: "	I am an ARDENT worker	",	turkish: "	I am a good worker	<br>	 İyi bir çalışanım	",	source: "	CELPIP-Word List	"},
{	id: "	337	",	french: "	I like to OVERCOME challenges	",	turkish: "	I like challenges	<br>	 Zorlukları severim	",	source: "	CELPIP-Word List	"},
{	id: "	338	",	french: "	My efforts MERIT my rewards	",	turkish: "	I don’t deserve it	<br>	 Bunu hak etmiyorum	",	source: "	CELPIP-Word List	"},
{	id: "	339	",	french: "	I am DESTINED to be a success	",	turkish: "	I do want to be a success in life	<br>	 Hayatta başarılı olmak istiyorum	",	source: "	CELPIP-Word List	"},
{	id: "	340	",	french: "	I am EMBOLDENED to move fast	",	turkish: "	Nothing can hold me back	<br>	 Hiçbir şey beni durduramaz	",	source: "	CELPIP-Word List	"},
{	id: "	341	",	french: "	lively	",	turkish: "	 fun or full of life	<br>	 canlı	",	source: "	CELPIP-Word List	"},
{	id: "	342	",	french: "	thrilling	",	turkish: "	 exciting	<br>	 heyecan verici	",	source: "	CELPIP-Word List	"},
{	id: "	343	",	french: "	festivity	",	turkish: "	 party	<br>	 şenlik, kutlama	",	source: "	CELPIP-Word List	"},
{	id: "	344	",	french: "	dine	",	turkish: "	 eat food	<br>	 yemek yemek	",	source: "	CELPIP-Word List	"},
{	id: "	345	",	french: "	tango	",	turkish: "	 dance (more used in formal/ballroom type dances)	<br>	 tango	",	source: "	CELPIP-Word List	"},
{	id: "	346	",	french: "	relish	",	turkish: "	 enjoy	<br>	 keyfini çıkarmak	",	source: "	CELPIP-Word List	"},
{	id: "	347	",	french: "	gratifying	",	turkish: "	 enjoyable	<br>	 memnun edici	",	source: "	CELPIP-Word List	"},
{	id: "	348	",	french: "	ecstatic	",	turkish: "	 very happy	<br>	 çok mutlu, mest olmuş	",	source: "	CELPIP-Word List	"},
{	id: "	349	",	french: "	giggle	",	turkish: "	 laugh	<br>	 kıkırdamak	",	source: "	CELPIP-Word List	"},
{	id: "	350	",	french: "	holler	",	turkish: "	 scream	<br>	 bağırmak	",	source: "	CELPIP-Word List	"},
{	id: "	351	",	french: "	mingle	",	turkish: "	 socialize	<br>	 karışmak, kaynaşmak	",	source: "	CELPIP-Word List	"},
{	id: "	352	",	french: "	grin	",	turkish: "	 smile	<br>	 sırıtmak	",	source: "	CELPIP-Word List	"},
{	id: "	353	",	french: "	berserk	",	turkish: "	 crazy	<br>	 çılgına dönmüş	",	source: "	CELPIP-Word List	"},
{	id: "	354	",	french: "	foolingaround	",	turkish: "	 acting like a crazy person	<br>	 oyalanmak, vakit geçirmek	",	source: "	CELPIP-Word List	"},
{	id: "	355	",	french: "	jest	",	turkish: "	 to express a joke	<br>	 şaka yapmak	",	source: "	CELPIP-Word List	"},
{	id: "	356	",	french: "	irate	",	turkish: "	 angry	<br>	 çok öfkeli	",	source: "	CELPIP-Word List	"},
{	id: "	357	",	french: "	antagonize	",	turkish: "	 make someone irritated	<br>	 düşman etmek, kışkırtmak	",	source: "	CELPIP-Word List	"},
{	id: "	358	",	french: "	salty(informal)	",	turkish: "	 irritated	<br>	 alıngan, sinirli	",	source: "	CELPIP-Word List	"},
{	id: "	359	",	french: "	pissedoff(informal)	",	turkish: "	 angry	<br>	 sinirli, çok kızgın	",	source: "	CELPIP-Word List	"},
{	id: "	360	",	french: "	exacerbate	",	turkish: "	 make something worse	<br>	 kötüleştirmek, şiddetlendirmek	",	source: "	CELPIP-Word List	"},
{	id: "	361	",	french: "	sulky	",	turkish: "	 uncooperative or bad-tempered	<br>	 somurtkan	",	source: "	CELPIP-Word List	"},
{	id: "	362	",	french: "	resentful	",	turkish: "	 hateful of somebody	<br>	 içerlemiş, kırgın	",	source: "	CELPIP-Word List	"},
{	id: "	363	",	french: "	abhor	",	turkish: "	 have disgust for something (verb)	<br>	 nefret etmek	",	source: "	CELPIP-Word List	"},
{	id: "	364	",	french: "	queasy	",	turkish: "	 feeling nauseated	<br>	 mide bulandırıcı	",	source: "	CELPIP-Word List	"},
{	id: "	365	",	french: "	haditwith/sickandtiredof	",	turkish: "	 completely annoyed with someone or something	<br>	 bıkmış, usanmış	",	source: "	CELPIP-Word List	"},
{	id: "	366	",	french: "	appalled	",	turkish: "	 horrified with something or someone	<br>	 dehşete düşmüş, şoke olmuş	",	source: "	CELPIP-Word List	"},
{	id: "	367	",	french: "	denounce	",	turkish: "	 accuse	<br>	 kınamak	",	source: "	CELPIP-Word List	"},
{	id: "	368	",	french: "	disparage	",	turkish: "	 degrade	<br>	 küçümsemek	",	source: "	CELPIP-Word List	"},
{	id: "	369	",	french: "	belittle	",	turkish: "	 make someone feel unimportant	<br>	 küçümsemek, önemsememek	",	source: "	CELPIP-Word List	"},
{	id: "	370	",	french: "	patronize	",	turkish: "	 insult someone in a way to degrade them	<br>	 tepeden bakmak, küçümsemek	",	source: "	CELPIP-Word List	"},
{	id: "	371	",	french: "	chaotic	",	turkish: "	 full of craziness or chaos (COVID stuff)	<br>	 kaotik, düzensiz	",	source: "	CELPIP-Word List	"},
{	id: "	372	",	french: "	segregated	",	turkish: "	 discriminative (mandates dividing people)	<br>	 ayrılmış, ayrıştırılmış	",	source: "	CELPIP-Word List	"},
{	id: "	373	",	french: "	progressive	",	turkish: "	 something that progresses into something positive	<br>	 ilerici	",	source: "	CELPIP-Word List	"},
{	id: "	374	",	french: "	turbulent	",	turkish: "	 fluctuating wildly (Crypto world)	<br>	 çalkantılı, fırtınalı	",	source: "	CELPIP-Word List	"},
{	id: "	375	",	french: "	unnerving	",	turkish: "	 causing one to lose courage (Taliban attack)	<br>	 sinir bozucu	",	source: "	CELPIP-Word List	"},
{	id: "	376	",	french: "	intriguing	",	turkish: "	 interesting (NFT creation online)	<br>	 ilgi çekici, merak uyandıran	",	source: "	CELPIP-Word List	"},
{	id: "	377	",	french: "	unearthing	",	turkish: "	 discovering something new (discovery of the ‘Southern’ Ocean)	<br>	 ortaya çıkarma, gün yüzüne çıkarma	",	source: "	CELPIP-Word List	"},
{	id: "	378	",	french: "	prodigious	",	turkish: "	 amazing (Richard Branson going into space)	<br>	 muazzam, olağanüstü	",	source: "	CELPIP-Word List	"},
{	id: "	379	",	french: "	ominous	",	turkish: "	 scary (natural disasters)	<br>	 uğursuz, kaygı verici	",	source: "	CELPIP-Word List	"},
{	id: "	380	",	french: "	cutthroat	",	turkish: "	 competitive (banks trying to compete with bitcoin)	<br>	 acımasız	",	source: "	CELPIP-Word List	"},
{	id: "	381	",	french: "	shortsighted	",	turkish: "	 silly (The US government vilifying billionaires)	<br>	 dar görüşlü	",	source: "	CELPIP-Word List	"},
{	id: "	382	",	french: "	aggrandizement	",	turkish: "	 growth (the growth of Tesla and Amazon)	<br>	 büyütme, yüceltme	",	source: "	CELPIP-Word List	"},
{	id: "	383	",	french: "	coercive	",	turkish: "	 forceful (forcing people to get the jab)	<br>	 zorlayıcı	",	source: "	CELPIP-Word List	"},
{	id: "	384	",	french: "	comical	",	turkish: "	 laughable (Sleepy Joe as the President)	<br>	 komik	",	source: "	CELPIP-Word List	"},
{	id: "	385	",	french: "	historical	",	turkish: "	something that will be remembered	<br>	 tarihi	",	source: "	CELPIP-Word List	"},
{	id: "	386	",	french: "	questionable	",	turkish: "	 controversial	<br>	 şüpheli	",	source: "	CELPIP-Word List	"},
{	id: "	387	",	french: "	lookssharp	",	turkish: "	 handsome; you can say he “looks sharp”	<br>	 şık görünüyor	",	source: "	CELPIP-Word List	"},
{	id: "	388	",	french: "	leftist	",	turkish: "	 communist	<br>	 solcu	",	source: "	CELPIP-Word List	"},
{	id: "	389	",	french: "	collected	",	turkish: "	 calm and soft-spoken	<br>	 sakin, derli toplu	",	source: "	CELPIP-Word List	"},
{	id: "	390	",	french: "	fascist	",	turkish: "	 dictator	<br>	 faşist	",	source: "	CELPIP-Word List	"},
{	id: "	391	",	french: "	triumphant	",	turkish: "	 successful	<br>	 zafer kazanmış, galip	",	source: "	CELPIP-Word List	"},
{	id: "	392	",	french: "	crook	",	turkish: "	 corrupt	<br>	 dolandırıcı	",	source: "	CELPIP-Word List	"},
{	id: "	393	",	french: "	amiable	",	turkish: "	 polite and friendly	<br>	 sevimli, cana yakın	",	source: "	CELPIP-Word List	"},
{	id: "	394	",	french: "	diplomatic	",	turkish: "	 someone who never picks a side	<br>	 diplomatik	",	source: "	CELPIP-Word List	"},
{	id: "	395	",	french: "	efficacious	",	turkish: "	 efficient or active	<br>	 etkili, verimli	",	source: "	CELPIP-Word List	"},
{	id: "	396	",	french: "	squanderer	",	turkish: "	 someone who spends money without thinking	<br>	 müsrif	",	source: "	CELPIP-Word List	"},
{	id: "	397	",	french: "	strategic	",	turkish: "	 careful in strategy	<br>	 stratejik	",	source: "	CELPIP-Word List	"},
{	id: "	398	",	french: "	megalomaniac	",	turkish: "	 hungry for power	<br>	 büyüklük hastası	",	source: "	CELPIP-Word List	"},
{	id: "	399	",	french: "	affluent	",	turkish: "	 rich	<br>	 varlıklı, zengin	",	source: "	CELPIP-Word List	"},
{	id: "	400	",	french: "	acclaimed	",	turkish: "	 known for	<br>	 beğenilen, övülen	",	source: "	CELPIP-Word List	"},

];
